// src/react/component/Calendar/Navigation.js
'use strict';

import React from 'react'
import PropTypes from 'prop-types'

import { 
	StyledCalendar
} from './calendar.style'

import Moment from 'moment'


const Navigation = ({decrementYear, incrementYear, apiCalendar, everything, target}) => {

	return (
		<nav>
			<button className="btn btn-primary" onClick={ decrementYear }>&lt;</button>
			
			<h2>
				React Calendar&nbsp;
				<span>{ everything.indexOf(apiCalendar) }</span>
			</h2>
			
			<button className="btn btn-primary" onClick={ incrementYear }>&gt;</button>

			<p>Target date: { Moment(target).format("dddd, Do MMM Y") }</p>
		</nav>
	)
}

export default Navigation;

// src/vue/component/calendar/Navigation.vue
<script>
'use strict';

export default {
	name: 'navigation',

	props: ["everything", "apiCalendar", "getTargetDate"],

	methods: {
		decrementYear(event){
			this.$emit('decrementYearEvent', event);
		},

		incrementYear(event){
			this.$emit('incrementYearEvent', event);
		}
	}
}
</script>

<template lang="pug">
	nav
		button.btn.btn-primary(v-on:click="decrementYear($event)") &lt;
		
		h2 Vue Calendar&nbsp;
			span {{ everything.indexOf(apiCalendar) }}
		
		button.btn.btn-primary(v-on:click="incrementYear($event)") &gt;
		
		p Target date: {{ getTargetDate }}
</template>

<style lang="scss" scoped>
</style>
